name: Nix CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-22.04
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main

      - name: Run `nix flake check`
        run: nix flake check

      - name: Run `nix build`
        run: nix build

      - name: Run `nix build .#fff-nvim`
        run: nix build .#fff-nvim

      - name: Run `nix run .#release`
        run: nix run .#release
