on:
  push:
    branches-ignore:
      - main
name: docs

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          # fetch last 2 commits required for auto force push back
          fetch-depth: 2

      - name: panvimdoc
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: fff.nvim
          version: "Neovim >= 0.10.0"
          demojify: true
          treesitter: true

      - name: Get last commit message
        id: last-commit
        run: |
          echo "message=$(git log -1 --pretty=%s)" >> $GITHUB_OUTPUT
          echo "author=$(git log -1 --pretty=\"%an <%ae>\")" >> $GITHUB_OUTPUT

      - uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_author: ${{ steps.last-commit.outputs.author }}
          commit_message: ${{ steps.last-commit.outputs.message }}
          commit_options: "--amend --no-edit"
          push_options: "--force"
